apiVersion: v2
name: airflow
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: airflow
  #version: 4.1.2 # NOPE
  #version: 4.10.0 # NOPE
  version: 6.10.4
  repository: https://charts.helm.sh/stable