apiVersion: v2
name: airflow
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: airflow
  version: 7.13.3
  repository: https://charts.helm.sh/stable